### ISSUE TITLE
Clean up the server code

### ISSUE THREAD

**Issue by GeorgeHahn** [GeorgeHahn/SOVND#124]
The current arrangement between `Server.cs` and `SortedPlaylistProvider` is unacceptable.
- [ ] Share code between `SortedPlaylistProvider` and `PlaylistProviderBase`
- [ ] Consolidate MQTT communication
- [ ] Consider breaking Redis functionality out to a separate class
